### PR TITLE
Solace Spring Cloud Version Upgrade

### PR DESCRIPTION
**Pull request by mayur-solace**
Update Solace Spring Cloud Version to [3.0.0](https://github.com/SolaceProducts/solace-spring-cloud/releases/tag/3.0.0)
Update Solace Spring Boot Version to [2.0.0](https://github.com/SolaceProducts/solace-spring-boot/releases/tag/2.0.0)
Update Spring Boot Version to 3.0.6
Changed Minimum JDK version required to JDK17

### CODE REVIEW

**Comment by mayur-solace** [comment]
@gvensan @Mrc0113  please review

**Comment by Mrc0113** [comment]
thank you @mayur-solace. @gvensan will take these for a spin next week and merge if all looks good!

**Comment by gvensan** [comment]
Looks good - tests passed.

**Review by gvensan — APPROVED** [review]
In progress.

**Review by gvensan — APPROVED** [review]
Looks good - with the actuator dependency added, it is complete. Thanks @mayur-solace

**Comment by Mrc0113** [comment]
@gvensan is this good to merge? If so, go ahead and "Squash and merge" please.

**Pull request merged**
